services:
  web:
    container_name: useradd
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/sika
    depends_on:
      - db
  db:
    container_name: postgresdb
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sika
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

